### PR TITLE
Add Unit Tests for the PickemPlayerComponent

### PR DESCRIPTION
**Pull request by keenanamigos**
Hello! I talked with you on Reddit about adding some unit tests to the project 😄 

The purpose of this PR was to add unit tests for the `PickemPlayerComponent`. Along the way I had to update some of the other spec files that were using incorrect imports and I also removed the `google-analytics.service.spec.ts` file entirely as there doesn't seem to be an associated service with this. 

## How to test:
Change `describe` [here](https://github.com/blubberbo/LolPickem/compare/master...keenanamigos:add-player-unit-tests?expand=1#diff-b104a79f48d4b8a7e54e7998ecf44d86L5) to be `fdescribe` so that it only runs the unit tests for the `PickemPlayerComponent`. There are other tests still failing so it's difficult to tell if these are passing otherwise. I'm planning on getting all of the unit tests passing as a baseline in a separate PR. Feel free to ask me any questions you have about the tests that I wrote and my thought process behind them 😄  

## Screenshots of passing unit tests:
Screen Shot 2020-04-05 at 10 59 24 PM

### CODE REVIEW

**Comment by blubberbo** [comment]
So I believe what I am supposed to do is run `ng test`, correct? 

I was not sure about the `Change describe here to be fdescribe so that it only runs the unit tests for the PickemPlayerComponent` comment. I changed `describe('PlayerComponent', () => {` to `fdescribe('PlayerComponent', () => {` on line 7 of `player.component.spec.ts` but it still looked as though it ran the tests for all the files.

The result in the browser I get is the following (and quite long): 
Screen Shot 2020-04-05 at 10 36 44 PM


I don't think that's right. Am I missing something?

Thank you for all your help!

**Comment by keenanamigos** [comment]
> So I believe what I am supposed to do is run `ng test`, correct?
> 
> I was not sure about the `Change describe here to be fdescribe so that it only runs the unit tests for the PickemPlayerComponent` comment. I changed `describe('PlayerComponent', () => {` to `fdescribe('PlayerComponent', () => {` on line 7 of `player.component.spec.ts` but it still looked as though it ran the tests for all the files.
> 
> The result in the browser I get is the following (and quite long):
> Screen Shot 2020-04-05 at 10 36 44 PM
> 
> I don't think that's right. Am I missing something?
> 
> Thank you for all your help!

Yes! Either `npm test` or `ng test` will run the test suite. But hmm...try making that same change from `describe` to `fdescribe`, make sure the test suite isn't running at all, and then run `npm test` or `ng test` again. It may have still been re-compiling when you took the screenshot after you hit save or something.

**Comment by blubberbo** [comment]
Ah got it, I will try again!

**Comment by blubberbo** [comment]
Ok got it working, that must have been it! Now I just need to find the time to read about how it works, haha.

Merging the PR now. Thanks!

**Comment by keenanamigos** [comment]
@blubberbo Thanks for merging! Always feel free to ask me any questions you about the tests and/or how things work 😄

**Pull request merged**
